ALTER TABLE proofs DROP COLUMN IF EXISTS content;
ALTER TABLE proofs ADD COLUMN IF NOT EXISTS event_count     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE proofs ADD COLUMN IF NOT EXISTS keystroke_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE proofs ADD COLUMN IF NOT EXISTS active_duration INTEGER NOT NULL DEFAULT 0;
